# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rooms/rooms.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rooms/rooms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rooms/rooms.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"\x17\n\x04Ping\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\r\"\x17\n\x04Pong\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\r2L\n\x0cRoomsService\x12<\n\x08PingPong\x12\x0b.proto.Ping\x1a\x0b.proto.Pong\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/ping-pong(\x01\x30\x01\x42\x16Z\x14proto/rooms/go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rooms.rooms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024proto/rooms/go/proto'
  _globals['_ROOMSSERVICE'].methods_by_name['PingPong']._loaded_options = None
  _globals['_ROOMSSERVICE'].methods_by_name['PingPong']._serialized_options = b'\202\323\344\223\002\014\022\n/ping-pong'
  _globals['_PING']._serialized_start=58
  _globals['_PING']._serialized_end=81
  _globals['_PONG']._serialized_start=83
  _globals['_PONG']._serialized_end=106
  _globals['_ROOMSSERVICE']._serialized_start=108
  _globals['_ROOMSSERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
