# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rooms import rooms_pb2 as rooms_dot_rooms__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rooms/rooms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingPong = channel.stream_stream(
                '/proto.RoomsService/PingPong',
                request_serializer=rooms_dot_rooms__pb2.Ping.SerializeToString,
                response_deserializer=rooms_dot_rooms__pb2.Pong.FromString,
                _registered_method=True)


class RoomsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingPong(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingPong': grpc.stream_stream_rpc_method_handler(
                    servicer.PingPong,
                    request_deserializer=rooms_dot_rooms__pb2.Ping.FromString,
                    response_serializer=rooms_dot_rooms__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RoomsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.RoomsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingPong(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/proto.RoomsService/PingPong',
            rooms_dot_rooms__pb2.Ping.SerializeToString,
            rooms_dot_rooms__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
